---
- name: "Converge"
  hosts: "cicd-debian-12"
  tasks:

    - name: "Include labocbz.add_php_fpm_confs"
      tags:
        - "labocbz.add_php_fpm_confs"
      vars:
        add_php_fpm_confs__php_version: "{{ inv_add_php_fpm_confs__php_version }}"
        add_php_fpm_confs__php_pools_path: "{{ inv_add_php_fpm_confs__php_pools_path }}"
        add_php_fpm_confs__fpm_pools: "{{ inv_add_php_fpm_confs__fpm_pools }}"
        add_php_fpm_confs__php_pools_log_path: "{{ inv_add_php_fpm_confs__php_pools_log_path }}"
      ansible.builtin.include_role:
        name: "labocbz.add_php_fpm_confs"
