---
# if you have any prepararion task
- name: "Prepare"
  hosts: "cicd-ubuntu-22"
  gather_facts: true
  tasks:

    - name: "Include cryptographic content var file"
      ansible.builtin.include_vars: "../../tests/certs/main.yml"

    - name: "Include labocbz.prepare_host"
      tags:
        - "labocbz.prepare_host"
      ansible.builtin.include_role:
        name: "labocbz.prepare_host"

    - name: "Gather facts from all hosts"
      delegate_to: "{{ item }}"
      delegate_facts: true
      loop: "{{ groups['cicd-ubuntu-22'] }}"
      ansible.builtin.setup:

    - name: "Edit /etc/hosts file to add all hosts"
      loop: "{{ groups['cicd-ubuntu-22'] }}"
      loop_control:
        loop_var: host
      register: output
      changed_when: output.rc != 0
      ansible.builtin.shell: "echo \"{{ hostvars[host]['ansible_default_ipv4']['address'] }}  {{ host }} # from Molecule\" >> /etc/hosts"

    - name: "Include labocbz.install_php"
      tags:
        - "labocbz.install_php"
      vars:
        install_php__version: "{{ inv_install_php__version }}"
        install_php__version_is_default: "{{ inv_install_php__version_is_default }}"
        install_php__extensions: "{{ inv_install_php__extensions }}"
        install_php__install_fpm: "{{ inv_install_php__install_fpm }}"
        install_php__import_cli_conf: "{{ inv_install_php__import_cli_conf }}"
        install_php__import_apache_conf: "{{ inv_install_php__import_apache_conf }}"
        install_php__import_cgi_conf: "{{ inv_install_php__import_cgi_conf }}"
        install_php__import_fpm_conf: "{{ inv_install_php__import_fpm_conf }}"
        install_php__max_input_time: "{{ inv_install_php__max_input_time }}"
        install_php__output_buffering: "{{ inv_install_php__output_buffering }}"
        install_php__cgi_fix_pathinfo: "{{ inv_install_php__cgi_fix_pathinfo }}"
        install_php__expose_php: "{{ inv_install_php__expose_php }}"
        install_php__max_execution_time: "{{ inv_install_php__max_execution_time }}"
        install_php__memory_limit: "{{ inv_install_php__memory_limit }}"
        install_php__post_max_size: "{{ inv_install_php__post_max_size }}"
        install_php__file_uploads: "{{ inv_install_php__file_uploads }}"
        install_php__upload_max_filesize: "{{ inv_install_php__upload_max_filesize }}"
        install_php__max_file_uploads: "{{ inv_install_php__max_file_uploads }}"
        install_php__allow_url_fopen: "{{ inv_install_php__allow_url_fopen }}"
        install_php__allow_url_include: "{{ inv_install_php__allow_url_include }}"
        install_php__session_save_handler: "{{ inv_install_php__session_save_handler }}"
        install_php__session_save_path: "{{ inv_install_php__session_save_path }}"
        install_php__session_auto_start: "{{ inv_install_php__session_auto_start }}"
        install_php__session_use_strict_mode: "{{ inv_install_php__session_use_strict_mode }}"
        install_php__disable_functions: "{{ inv_install_php__disable_functions }}"
        install_php__log_level: "{{ inv_install_php__log_level }}"
      ansible.builtin.include_role:
        name: "labocbz.install_php"
